name: GitHub Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --force
      - name: build project
        run: npm run build
      - name: unit test
        run: npm run test
      - name: e2e test
        run: npm run cypress
      - name: lint code
        run: npm run lint
      - name: format code
        run: npm run format